controller:
  replicaCount: 2
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
    limits:
      cpu: 500m
      memory: 500Mi
  nodeSelector:
    kubernetes.io/os: linux
  service:
    type: LoadBalancer
    annotations:
  ingressClassResource:
    name: nginx
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"
  metrics:
    enabled: true
    serviceMonitor:
      enabled: false  
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  admissionWebhooks:
    enabled: true
    patch:
      enabled: true
      nodeSelector:
        kubernetes.io/os: linux
  config:
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    ssl-redirect: "false" 
    proxy-body-size: "1m"
    proxy-read-timeout: "60"
    proxy-send-timeout: "60"
defaultBackend:
  enabled: true
  replicaCount: 1
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    requests:
      cpu: 10m
      memory: 20Mi
    limits:
      cpu: 20m
      memory: 30Mi
rbac:
  create: true
serviceAccount:
  create: true
  name: ""
