apiVersion: apps/v1
kind: Deployment
metadata:
  name: navatech-assignment
  namespace: default
spec:
  replicas: 3  
  selector:
    matchLabels:
      app: navatech-assignment
  strategy:
    type: RollingUpdate  
    rollingUpdate:
      maxUnavailable: 0  
      maxSurge: 1        
  template:
    metadata:
      labels:
        app: navatech-assignment
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3  
        ports:
        - containerPort: 80
        resources:
          requests:  
            cpu: "100m"
            memory: "128Mi"
          limits:   
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_PORT
        readinessProbe:  
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:   
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        volumeMounts:
        - name: nginx-index
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-index
        configMap:
          name: nginx-index-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Assignment</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          margin: 40px;
          text-align: center;
        }
        .container {
          max-width: 800px;
          margin: 0 auto;
        }
        h1 {
          color: #3498db;
        }
        .info {
          background-color: #f8f9fa;
          border: 1px solid #dee2e6;
          border-radius: 5px;
          padding: 20px;
          margin: 20px 0;
        }
      </style>
    </head>
    <body>
      <div class="container">

        <div class="info">
          <p><strong>Welcome to the Kubernetes Assignment!</strong></p>

        </div>
      </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: navatech-assignment
spec:
  selector:
    app: navatech-assignment
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
---



apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: navatech-assignment-pdb
spec:
  minAvailable: 2  
  selector:
    matchLabels:
      app: navatech-assignment
---



apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: navatech-assignment-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: navatech-assignment
  minReplicas: 3  
  maxReplicas: 10  
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  